### ISSUE TITLE
[feature request] file names in pretty print

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#10]
file names in pretty print when there is more than 1 file because of includes

<img width="45" alt="image" src="https://user-images.githubusercontent.com/677956/170903977-ded0045a-d33f-445e-9687-cd4cf049b3c6.png">

**Comment by michaelkamprath** [comment]
Yeah, I was planning on overhauling pretty print to allow user definable formats. This issue is one of the motivators.
