### ISSUE TITLE
[feature idea] relative jump

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#17]
for relative jumps the offset from the current position to the label needs to be calculated.

```
    RJMP label
    nop
label:
```
needs to emit "0x<rjmp_opcode> 0x02"

offset bounds need to be defined (for example -127 to +127) and compilation needs to throw an error if the calculated offset exceeds the bounds and also a additional fixed offset needs to be configurable in isa.yaml which will be added, because the current value of the programm counter may be at the opcodes position, the parameters position or even 1 after that depending on programcounter incrementor design. it needs to respect the architectures word size also.

most (real world) architectures have relative jumps.

(low priority for me, but it's on my todo list to optimize the architecture for clock efficency and this is a low hanging fruit, makes software-division/multiply noticably faster, because a high percentage of the instructions are jumps)

**Comment by michaelkamprath** [comment]
Yeah, I have been mean to add a relative address operand  that calculates the delta between the target address and the current address and its that difference as an argument subject to some bounds. This is actually pretty easy to do in the code base.

The only thing I haven't sorted out is the notation for this. Sometimes the instruction itself indicates that operand should be a relative jump value, sometimes the operand has specific notation that indicates it's a relative jump operand. For example, in BespokeASM uses `[addr]` for indirect operands, and ``[[addr]]`` for deferred. Most assembly languages I know have a separate instruction for relative jumps and thus don't have any sort of punctuation notation to indicate the operand is a relative address. But if we had punctuation, the instruction signature (mnemonic + operands types) would select the overall byte code for the instruction. I was thinking of using the curly braces `{` `}` to indicate the expression they contain should be interpreted as a relative address. 

That is, notation could be:

```asm
rjmp label
```

or

```asm
jump {label}
```

I think the Curley braces would enable richer options for instruction signatures, but it is nonstandard (not that there is any real standard in assembly). What are you thoughts?

**Comment by sebseb7** [comment]
I see. I have no preference.

while we're at relative addresses. I have no idea how the notation would make sense, and I also never have seen this anywhere. But one thing would be extremely useful:

a label for stack positions (offsets)

```
    ld a,0x42 ; var_x
    push a
    ld a,0x23 ; var_y
    push a
    
    ld a,[sp+1] ; stackpointer=var_y, stackpointer+1 = var_x
    
    ld a,0xff ; var_z
    push a
    
    ld a,[sp+2] ; stackpointer=var_z, stackpointer+1 = var_y, stackpointer+2 = var_x
```

sometimes it's hard to keep track of this, and everytime you insert something, you'll have to update all the stackpointer offsets.

to make this work the assembler needs to know which instructions modify the stackpointer and I have no idea how the labels would look like.

**Comment by michaelkamprath** [comment]
I will tell you, I would love a stack position label. I too struggle with keeping track of where something is in the stack. I have some ideas on how to do it but it would be limited to only local scope. But the reason I haven't implemented it is because my idea will fail the code does stack push/pops in a dynamic loop. I need to think about it more, or simply have caveats on when the stack label will fail.

**Comment by michaelkamprath** [comment]
I added a relative address operand. An example operand configuration would be:

```yaml
...
      specific_operands:
        relative_addr:
          list:
            relative_addr:
              type: relative_address
              offset_from_instruction_end: true
              use_curly_braces: false
              argument:
                size: 8
                byte_align: true
                max: 128
                min: -127
...
```
The option `use_curly_braces` indicates whether the operand uses curly braces `{ }` to notate the operand type or not, and `offset_from_instruction_end` determines what program counter value the offset should be relative to: the beginning of the instruction (`false`) or the end of the instruction (`true`).
