### ISSUE TITLE
In kenbak-1, instructions using Indirect Indexed mode do not compile.

### ISSUE THREAD

**Issue by zuchodrig** [michaelkamprath/bespokeasm#25]
test.kb1

`ld a, [x+[2]]`

bespokeasm compile -c kenbak-1-isa.yaml test.kb1
result:
ERROR: file test.kb1, line 1 - Instruction "ld" has no valid operands configured.

apparently [x+[2]] can't be matched with regexp
`^\[\s*(x)\s*(\+|\-)\s*(^\[\s*((?:[\$\%\w\(\)\+\-\s]*[\w\)]))\s*\]$)\s*\]$`
probably because of second caret (and matching $) in the middle of regexp.
Which comes from match_pattern(self) in indirect_numeric.py

**Comment by michaelkamprath** [comment]
Hmmm, looks like I introduced this bug recently. Thanks, I will get it addressed.

**Comment by michaelkamprath** [comment]
@zuchodrig I believe I have fixed this bug with #26 . Please try with the HEAD commit and tell me if it works better for you.

**Comment by zuchodrig** [comment]
@michaelkamprath  yes, works now.
