### ISSUE TITLE
[feature request] redefineable labels

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#9]
It would be nice to have included libraries to add code to multiple sections. therefore one needs a label that points to the end of that section which can be redefined.

main file:

```
.org 0x0000 ; RAM
ramEND:

.org 0x8000 ; ROM
	ld a,50
	call [set_seed]
	hlt
romEND:

#include "lib.asm"
```

lib.asm:
```
.org ramend
seed
    .byte 0
ramend:

.org romEND
set_seed:
	st a,[seed]
	ret	
romEND:
```

**Comment by michaelkamprath** [comment]
I have been thinking about this problem for some time, and am gravitating towards a different approach. What I was thinking was to define (through a preprocessor directive) a "memory block", and then you can define a block of code or data to bye in that memory block. These memory blocks can be globally or locally defined. BespokeASM would then take all of the stuff assigned to a given memory block and pack them together, error if it all added up to more than the allocated block. The syntax I was thinking is similar to the `.org` directive, but the argument would be the name of a defined memory block. 

The main use case I was thinking about was serving a section of RAM for kernel use, and then kernel code can just create data blocks (variables) in the kernel memory block without needing to (at coding time) be pedantic about specific memory addresses. 

The same approach would work with code and ROM.

Thoughts?

**Comment by sebseb7** [comment]
👍

**Comment by michaelkamprath** [comment]
So I am going to use this thread to document and iterate on some requirements for this feature. Please feel free to comment.

## Overview
The general goal is to create the ability to define at compile time memory ranges that can be referred to by name. Once defined, the named memory space can be used in the following manners:

1. a  directive can set the current address address as an offset within the named memory space.
2. a directive that indicates the subsequent code/data should be in the named memory space but leave it up to the compiler to set the exact address (usually just set the address in the order that the code is assembled). This would work across multiple disjoint references to the named memory block.

Named memory blocks are a compilation

## Requirements
### Named Memory Blocks
A named memory block is a contiguous address range in the allowable address space of a given ISA that has an alphanumeric string as an identifier. The following additional conditions apply:

* A named memory block must be completely contained by the allowed memory space of the configured ISA.
* Multiple named memory blocks may overlap with each other
* When byte code is assembled, multiple byte codes assigned to the same absolute memory address is a fatal error.
* Named memory blocks are a compile time construct, and are intended to only be a means to manage memory ranges and byte code memory locations in assembly code. 
* Memory blocks have a start and end absolute memory address. Byte code assigned to that memory block with an absolute address outside of the memory block's range will be an error.
* A memory block's name cannot be also used for any label.

#### Creation

##### In Code
A memory block can be defined with the following directive

#memblock "<memory block name>" <start address> <end address>

Where `<memory block name>` is an alphanumeric string with no spaces which will serve as the memory block name, `<start address>` is the absolute address of the start of the memory block, and `<end address>` is the absolute address of the end of the memory block.

##### ISA Configuration
A predefined memory block can be defined in the instruction set configuration file. See the configuration file schema specification.

##### Global Memory Block
By default, a memory block named `GLOBAL` is defined to be the full range of memory addressed allowed by the instruction set configuration file. For example, if the ISA defines a 16-bit address type, then the `GLOBAL` memory block will be addresses `0x0000` though `0xFFFF`. 

### Address Origin Setting
The `.org` directive will be updated to support the following syntaxes:

#### Memory Block Scope
By default, code in any given source file is assembled into the `GLOBAL` memory block scope. To set the current memory block scope to something different, the following directive is used:

```asm
.curmemblock "<memory block name>"
```

Note that the `GLOBAL` memory block name can be used this directive. Subsequant assembly code lines will be compiled into the indicated memory block scope until the end of the current assembly file or another directive that changes the memory block scope. Addresses assigned to the byte code will be per the code ordering. 

Non-contiguous uses of a given memory block scope will be compiled as if the assembly code in each use instance was concatenated together in the order processed by the assembler.

If a source file that is currently using a non-`GLOBAL` memory block includes another source file, that included source file will be compiled into the `GLOBAL` memory block scope per normal file processing as described above. When compilation returns to the original source file that included the additional source file, compilation will continue using the same memory block scope that was active when the `#include` directive was processed. This means that source files must always declare any non-`GLOBAL` emory block scope they wish to use, and such declarations only persist for the scope of that source file.

#### Relative Origin within a Memory Block
A relative origin within a memory block can be set with the `.org` directive:

```asm
.org <address offset value> "<memory block name>"
```

Where `<address offset value>` is the positive offset from the start of the specific memory block, and `<memory block name>` is the name of the specified memory block (which is optional, see below). So, if a memory block named "variables" is defined to be the range of `0x2000` through `0x2FFF`, then:

```asm
.org 0x0100 "variables"
```

Would be the same as setting the current origin to `0x2100` in the `GLOBAL` scope. 

Not specifying a `<memory block name>` implies the `GLOBAL` scope and the provided offset is applied to the start of the overall address range for the configured instruction set. Note that the `GLOBAL` memory block name cane be used in `<memory block name>` if desired for clarity.

**Comment by michaelkamprath** [comment]
This feature is currently being worked on in the `memory-zones` branch.
